### ISSUE TITLE
Mod ebb uses the version 1.18.X-1.0.0 which isn't compatible with Loader's extended semantic version format

### ISSUE THREAD

**Issue by Kino0208** [Nova-Committee/Elytra-Bombing#1]
Mod ebb uses the version 1.18.X-1.0.0 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'X'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version

Mod ebb 使用的版本 1.18.X-1.0.0 与 Loader 的扩展语义版本格式不兼容（无法解析版本号组件'X'！），建议使用 SemVer 可靠地评估依赖关系并优先考虑新版本

**Comment by VulpesStella** [comment]
You can manually modify it.
